Backend/routes.py
import os
from flask import Flask, render_template, flash, request, redirect, url_for, session, abort, Blueprint
# Various imports for the Flask application, including extensions
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField, ValidationError, SelectField,TextAreaField
from wtforms.validators import DataRequired, EqualTo, Length
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from datetime import datetime
from wtforms.widgets import TextArea
from flask_login import UserMixin, login_user, LoginManager, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy import desc
from sqlalchemy.orm import relationship
import time
from models import *
from functions import *
from forms import *


main_bp = Blueprint('main', __name__)
## Routes ##
@main_bp.route('/') # Root
def default():
    return redirect(url_for('main.f_login'))


@main_bp.route('/index') #Homepage
def index():
    user_role = session.get('user_role')
    if current_user.is_authenticated and user_role == 'professor':
        # If the logged-in user is a professor, fetch their specific reviews
        professor_reviews = Professor_Posts.query.filter_by(professor_name=current_user.name).order_by(Professor_Posts.rating.desc()).limit(5).all()
        return render_template('index.html', professor_posts=professor_reviews, class_posts=None)
    else:
        reviews_table1 = Professor_Posts.query.order_by(Professor_Posts.rating.desc()).limit(5).all()
        reviews_table2 = Class_Posts.query.order_by(Class_Posts.rating.desc()).limit(5).all()
        return render_template('index.html', professor_posts=reviews_table1, class_posts=reviews_table2)


# Invalid route(s) or server error
@main_bp.errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404
@main_bp.errorhandler(500)
def page_not_found(e):
    return render_template("500.html"), 500


@main_bp.route('/f_users_posts/delete/<string:post_type>/<int:post_id>')
@login_required
def delete_post(post_type, post_id):
    if post_type == 'class':
        post = Class_Posts.query.get(post_id)
    elif post_type == 'professor':
        post = Professor_Posts.query.get(post_id)


    # Check if the current user is the author of the post
    # Delete the post
    if post and post.student_name == current_user.name:
        # Delete the post
        db.session.delete(post)
        db.session.commit()
        # flash("Post deleted", "success")
    else:
        abort(403)

    # Redirect to the user's posts page
    return redirect(url_for('main.f_dashboard'))


@main_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        role = determine_user_role(username)
        form.role.data = role 

        if role == 'student':
            user = Students.query.filter_by(username=form.username.data).first()
        elif role == 'professor':
            user = Professors.query.filter_by(username=form.username.data).first()

        if user:
            if check_password_hash(user.password_hash, form.password.data):
                login_user(user)
                # flash("You are now logged in")
                return redirect(url_for('dashboard'))
            else:
                flash("Incorrect password")
        else:
            flash("No such user exists")
    
    return render_template("login.html", form=form)

@main_bp.route('/logout', methods= ['GET', 'POST'])
@login_required
def logout():
    session.pop('user_role', None)
    return redirect(url_for('main.f_login'))

# Profile
@main_bp.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    form = LoginForm()
    return render_template('dashboard', form=form)


@main_bp.route('/f_addProfessor', methods=['GET', 'POST'])
def f_addProfessor():
    name = None
    form = ProfForm()  # Assuming the UserForm is updated to include the necessary fields for professors

    if form.validate_on_submit():
        user = Professors.query.filter_by(email=form.email.data).first()  # Use Professors model
        if user is None:
            hashed_pw = generate_password_hash(form.password_hash.data, "sha256")
            user = Professors(
                username=form.username.data,
                name=form.name.data,
                email=form.email.data,
                birthday=form.birthday.data,  # Add the birthday field
                teacher_id=form.teacher_id.data,  # Add the teacher_id field
                school_id=form.school_id.data,
                password_hash=hashed_pw
            )
            db.session.add(user)
            db.session.commit()

            name = form.name.data
            form.name.data = ''
            form.username.data = ''
            form.email.data = ''
            form.birthday.data = ''
            form.teacher_id.data = ''
            form.school_id.data = ''
            form.password_hash.data = ''

            # flash("Professor registration completed")
            return redirect(url_for('main.f_login'))

    return render_template("f_addProfessor.html", form=form, name=name)


    
@main_bp.route('/main.f_addstudent', methods=['GET', 'POST'])
def f_addstudent():
    name = None
    form = UserForm()  # Assuming the UserForm is updated to include the necessary fields for students

    if form.validate_on_submit():
        user = Students.query.filter_by(email=form.email.data).first()  # Use Students model
        if user is None:
            hashed_pw = generate_password_hash(form.password_hash.data, "sha256")
            user = Students(
                username=form.username.data,
                name=form.name.data,
                email=form.email.data,
                birthday=form.birthday.data,  # Add the birthday field
                major=form.major.data,  # Add the major field
                student_id=form.student_id.data,
                school_id=form.school_id.data,
                password_hash=hashed_pw
            )
            db.session.add(user)
            db.session.commit()

            name = form.name.data
            form.name.data = ''
            form.username.data = ''
            form.email.data = ''
            form.birthday.data = ''
            form.major.data = ''
            form.student_id.data = ''
            form.school_id.data = ''
            form.password_hash.data = ''

            # flash("Student registration completed")
            return redirect(url_for('main.f_login'))

    return render_template("f_addstudent.html", form=form, name=name)
    # return render_template("login.html")



# F_DASHBOARD
@main_bp.route('/f_dashboard', methods=['GET', 'POST'])
@login_required
def f_dashboard():
    form = LoginForm()
    user_role = session.get('user_role', None)
    return render_template('f_dashboard.html', form=form,user_role=user_role)


@main_bp.route('/f_login', methods=['GET', 'POST'])
def f_login():
    form = LoginForm()
    if form.validate_on_submit():
        student = Students.query.filter_by(username=form.username.data).first()
        professor = Professors.query.filter_by(username=form.username.data).first()
        if student and check_password_hash(student.password_hash, form.password.data):
            login_user(student)
            user_role = "student"
            session['user_role'] = user_role
            # flash("You are now logged in as a student")
            return redirect(url_for('main.f_dashboard', user_role=user_role))
        elif professor and check_password_hash(professor.password_hash, form.password.data):
            login_user(professor)
            user_role = "professor"
            session['user_role'] = user_role
            # flash("You are now logged in as a professor")
            return redirect(url_for('main.f_dashboard', user_role=user_role))
        else:
            flash("Incorrect username or password")
    return render_template('f_login.html', form=form)

#F_LOGOUT
@main_bp.route('/f_logout', methods= ['GET', 'POST'])
@login_required
def f_logout():
    session.pop('user_role', None)
    print(session.user_role)
    logout_user()
    # flash("You are now logged out")
    return redirect(url_for('main.f_login'))


# F_DELETE
@main_bp.route('/f_delete/<int:id>')
@login_required
def f_delete(id):
    if id == current_user.id:
        # Determine user_type based on the id
        user_to_delete = Students.query.get(id)
        if user_to_delete is None:
            user_to_delete = Professors.query.get(id)

        if user_to_delete:
            # Determine user type and select the appropriate form
            if isinstance(user_to_delete, Students):
                user_type = 'student'
                user_id = user_to_delete.id
                form = UserForm()
            elif isinstance(user_to_delete, Professors):
                user_id = user_to_delete.id
                user_type = 'professor'
                form = ProfForm()
            else:
                # flash("Invalid user type")
                return redirect(url_for('some_error_route'))
        else:
            # flash("User not found")
            return redirect(url_for('some_error_route'))

        try:
            db.session.delete(user_to_delete)
            db.session.commit()
            # flash("User profile deleted")

            # Redirect to a suitable template
            return redirect(url_for('main.f_dashboard'))

        except Exception as e:
            # flash("Whoops! There was a problem deleting the user, try again...")
            return redirect(url_for('main.f_dashboard'))
    else:
        # flash("Deletion failed")
        return redirect(url_for('main.f_dashboard'))



@main_bp.route('/f_update/<int:id>', methods=['GET', 'POST'])
@login_required
def f_update(id):
    # Determine user_type based on the id

Backend/templates/aboutus.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>About Us</title>
  <!-- Google Fonts link for 'Mooli' -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Mooli&display=swap" rel="stylesheet">
  <!-- Link to your existing stylesheet -->
  <link rel="stylesheet" href="/static/screen.css">
  <style>
    body {
      font-family: 'Mooli', sans-serif;
    }
    .centered-content {
      text-align: center; /* Center text */
      margin: auto; /* Center the container */
      max-width: 800px; /* Maximum width of the container */
      padding: 20px; /* Padding for aesthetics */
      /* Additional styling if needed */
    }
    .centered-content p {
      margin-bottom: 20px; /* Space between paragraph and button */
    }
    .container-404 h1 {
      margin-top: 30px; /* Space above the About Us heading */
    }
  </style>
</head>

<body>
  <header id="header">
    <h1>Welcome to Course-Reviewer!</h1>
    <nav id="site-nav">
      <ul>
        <li>
          <h3><a href="{{ url_for('main.index') }}"></a><img src="/static/icon.png" alt="Class Champion Logo"></a></h3>
        </li>
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.index')}}">Home</a></li>
        {% if session.get('user_role') == 'student' %}
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_class')}}">Classes</a></li>
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_professors')}}">Professors</a></li>
        {% endif %}
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_help')}}">Help</a></li>
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_dashboard')}}">Account</a></li>
        <!-- Updated href attribute -->
        {% if current_user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.logout')}}">Logout</a></li>
        {% if current_user.username == 'admin' %}
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.addClass')}}">Add Classes</a></li>
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.addProfessor')}}">Add Professors</a></li>
        {% endif %}
        {% else %}
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_login')}}">Login</a></li>

        {% endif %}
        <li>
          <form method="POST" action="{{url_for('main.search')}}">
            <div class="search-container">
              {{form.hidden_tag()}}
              <input type="text" name="searched" class="form-control me-2" placeholder="Class/Professor">
              <button id="searchButton" type="submit">Search</button>
            </div>
          </form>
        </li>

      </ul>
    </nav>
  </header><main>
  <div class="container-404">
    <h1>About Us</h1>
    <div class="centered-content">
      <p>Our team consists of four innovative students from Illinois Tech. Our academic backgrounds include ITM, CS, and DS. We are passionate about leveraging our skills to develop platforms that enrich the educational experience for students worldwide.
        
      </p>
      <a href="/" class="btn btn-primary">Go Home</a>
    </div>
    
  </div>
</main>
  <footer id="footer">

    <ul>
      <li><a href="{{ url_for('main.aboutus') }}">About Us</a></li>
      <li><a href="{{ url_for('main.ourMission') }}">Our Mission</a></li>
      <li><a href="{{ url_for('main.contactUs') }}">Contact Us</a></li>
      <li><a href="{{ url_for('main.futurePlans') }}">Future Plans</a></li>



    </ul>
    <p>Site content for Course Reviewer (Group E)</p>
  </footer>
</body>

</html>

Backend/templates/addClass.html
<!DOCTYPE html>
{% block content %}
<html lang="en">

{% for message in get_flashed_messages() %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
  {{message}}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Mooli&display=swap" rel="stylesheet">

<head>
  <meta charset="utf-8" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='screen.css') }}" />
</head>

<body>
  <header id="header">
    <h1>Class Add Page</h1>
    <nav id="site-nav">
      <ul>
        <li>
          <h3><a href="{{ url_for('main.index') }}"></a><img src="/static/icon.png" alt="Class Champion Logo"></a></h3>
        </li>
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.index')}}">Home</a></li>
        {% if session.get('user_role') == 'student' %}
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_class')}}">Classes</a></li>
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_professors')}}">Professors</a></li>
        {% endif %}
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_help')}}">Help</a></li>
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_dashboard')}}">Account</a></li>
        <!-- Updated href attribute -->
        {% if current_user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.logout')}}">Logout</a></li>
        {% if current_user.username == 'admin' %}
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.addClass')}}">Add Classes</a></li>
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.addProfessor')}}">Add Professors</a></li>
        {% endif %}
        {% else %}
        <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_login')}}">Login</a></li>

        {% endif %}
        <li>
          <form method="POST" action="{{url_for('main.search')}}">
            <div class="search-container">
              {{form.hidden_tag()}}
              <input type="text" name="searched" class="form-control me-2" placeholder="Class/Professor">
              <button id="searchButton" type="submit">Search</button>
            </div>
          </form>
        </li>

      </ul>
    </nav>
  </header>
  <main id="content">
    <section class="classSection" id="review-container">
      <h1>Make the Class</h1>
      <form id="review-form" method="POST">
        {{ form.hidden_tag() }} {# Add the CSRF token #}

        <label for="class_name">Class Name:</label>
        {{ form.class_name(class="your-css-class") }}

        <label for="class_number">Class Number(ex. CS422):</label>
        {{ form.name(class="your-css-class") }}

        <label for="description">Class Description:</label>
        {{ form.description(class="your-css-class") }}

        <button type="submit" id="subRevBtn" onclick="this.disabled=true;this.form.submit();">Submit Class</button>

      </form>
    </section>




  </main>
  <footer id="footer">

    <ul>
      <li><a href="{{ url_for('main.aboutus') }}">About Us</a></li>
      <li><a href="{{ url_for('main.ourMission') }}">Our Mission</a></li>
      <li><a href="{{ url_for('main.contactUs') }}">Contact Us</a></li>
      <li><a href="{{ url_for('main.futurePlans') }}">Future Plans</a></li>



    </ul>
    <p>Site content for Course Reviewer (Group E)</p>
  </footer>
</body>

</html>
{% endblock %}

Backend/templates/f_dashboard.html
<!DOCTYPE html>
{% block content %}
<html lang="en">

{% for message in get_flashed_messages() %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Mooli&display=swap" rel="stylesheet">

<head>
    <meta charset="utf-8" />
    <title>Account Page</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='screen.css') }}" />
</head>

<body>
    <header id="header">
        <h1>Account Page</h1>

        <nav id="site-nav">
            <ul>
              <li>
                <h3><a href="{{ url_for('main.index') }}"></a><img src="/static/icon.png" alt="Class Champion Logo"></a></h3>
              </li>
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.index')}}">Home</a></li>
              {% if session.get('user_role') == 'student' %}
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_class')}}">Classes</a></li>
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_professors')}}">Professors</a></li>
              {% endif %}
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_help')}}">Help</a></li>
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_dashboard')}}">Account</a></li>
              <!-- Updated href attribute -->
              {% if current_user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.logout')}}">Logout</a></li>
              {% if current_user.username == 'admin' %}
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.addClass')}}">Add Classes</a></li>
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.addProfessor')}}">Add Professors</a></li>
              {% endif %}
              {% else %}
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_login')}}">Login</a></li>
      
              {% endif %}
              <li>
                <form method="POST" action="{{url_for('main.search')}}">
                  <div class="search-container">
                    {{form.hidden_tag()}}
                    <input type="text" name="searched" class="form-control me-2" placeholder="Class/Professor">
                    <button id="searchButton" type="submit">Search</button>
                  </div>
                </form>
              </li>
      
            </ul>
          </nav>

    </header>
    <main id="content">

        <section id="account-info">
            <h2>Account Information</h2>
            <br>
            <ul id="account_list">
                <li>
                    <span>Name:</span>
                    <span id="Account_Name">{{ current_user.name }}</span>
                </li>
                <li>
                    <span>Username:</span>
                    <span id="Account_Name">{{ current_user.username }}</span>
                </li>
                {% if user_role == 'student' %}
                <li>
                    <span>Student ID:</span>
                    <span id="Account_Name">{{ current_user.student_id }}</span>
                </li>
                <li>
                    <span>Major:</span>
                    <span id="Account_major">{{ current_user.major }}</span>
                </li>
                {% elif user_role == 'professor' %}
                <li>
                    <span>Teacher ID:</span>
                    <span id="Account_teacher_id">{{ current_user.teacher_id }}</span>
                </li>
                {% endif %}
                <li>
                    <span>Email:</span>
                    <span id="Account_email">{{ current_user.email }}</span>
                </li>
                <li>
                    <span>University:</span>
                    <span id="Account_school">{{ current_user.school_id }}</span>
                </li>
                <li>
                    <span>Date Joined:</span>
                    <span id="Account_Name">{{ current_user.date_added.strftime('%m/%d/%Y') }}</span>
                </li>
            </ul>
            <br>
            <br>


            <a href="{{ url_for('main.f_logout') }}">
                <button class="small-button">Logout</button>
            </a>
            <a href="{{ url_for('main.f_update', id=current_user.id) }}">
                <button class="small-button">Update</button>
            </a>
            <a href="{{ url_for('main.f_delete', id=current_user.id) }}">
                <button class="small-button">Delete</button>
            </a>
            <a href="{{ url_for('main.f_users_posts', username=current_user.username) }}">
                <button class="small-button">Your Posts</button>
            </a>

        </section>

    </main>

    <footer id="footer">

        <ul>
            <li><a href="{{ url_for('main.aboutus') }}">About Us</a></li>
            <li><a href="{{ url_for('main.ourMission') }}">Our Mission</a></li>
            <li><a href="{{ url_for('main.contactUs') }}">Contact Us</a></li>
            <li><a href="{{ url_for('main.futurePlans') }}">Future Plans</a></li>



        </ul>
        <p>Site content for Course Reviewer (Group E)</p>
    </footer>
</body>

</html>
{% endblock %}

Backend/templates/f_login.html
<!DOCTYPE html>
{% block content %}

<html lang="en">

{% for message in get_flashed_messages() %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}


<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Mooli&display=swap" rel="stylesheet">

<head>
  <meta charset="utf-8" />
  <title>Homepage</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='screen.css') }}" />
</head>

<body>

  <header id="header">
    <h1>Login</h1>

    <nav id="site-nav">
      <ul>
        <li>
          <h3><a href="{{url_for('main.index')}}"> <img src="/static/icon.png" alt="Class Champion Logo"></a></h3>
        </li>
      </ul>
    </nav>
  </header>

  <main id="content">

    <p>

    </p>
    </br></br>
    <section>
      <form method="POST">

        {{ form.hidden_tag() }}
        {{ form.username.label(class="form-label") }}
        {{ form.username(class="form-control") }}
        {{ form.password.label(class="form-label") }}
        {{ form.password(class="form-control") }}
        </br></br>
        {{ form.submit(class="btn btn-secondary")}}
        </br>
      </form>

      <!-- <a href='user/f_addStudent'><button class="regBtn">Student Register</button></a> -->
      <a href="{{ url_for('main.f_addstudent') }}"><button class="regBtn">Student Register</button></a>
      <!-- <a href='user/f_addProfessor'><button class="regBtn">Professor Register</button></a> -->
      <a href="{{ url_for('main.f_addProfessor') }}"><button class="regBtn">Professor Register</button></a>
    </section>
  </main>
  <footer id="footer">

    <ul>
      <li><a href="{{ url_for('main.aboutus') }}">About Us</a></li>
      <li><a href="{{ url_for('main.ourMission') }}">Our Mission</a></li>
      <li><a href="{{ url_for('main.contactUs') }}">Contact Us</a></li>
      <li><a href="{{ url_for('main.futurePlans') }}">Future Plans</a></li>



    </ul>
    <p>Site content for Course Reviewer (Group E)</p>
  </footer>
</body>

</html>
{% endblock %}

Backend/templates/f_users_posts.html
<!DOCTYPE html>
{% block content %}
<html lang="en">

{% for message in get_flashed_messages() %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Mooli&display=swap" rel="stylesheet">

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='screen.css') }}" />
</head>

<body>
    <header id="header">
        <h1>Class Page: {{ course_name }}</h1>
        <nav id="site-nav">
            <ul>
              <li>
                <h3><a href="{{ url_for('main.index') }}"></a><img src="/static/icon.png" alt="Class Champion Logo"></a></h3>
              </li>
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.index')}}">Home</a></li>
              {% if session.get('user_role') == 'student' %}
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_class')}}">Classes</a></li>
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_professors')}}">Professors</a></li>
              {% endif %}
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_help')}}">Help</a></li>
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_dashboard')}}">Account</a></li>
              <!-- Updated href attribute -->
              {% if current_user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.logout')}}">Logout</a></li>
              {% if current_user.username == 'admin' %}
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.addClass')}}">Add Classes</a></li>
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.addProfessor')}}">Add Professors</a></li>
              {% endif %}
              {% else %}
              <li class="nav-item"><a class="nav-link" href="{{url_for('main.f_login')}}">Login</a></li>
      
              {% endif %}
              <li>
                <form method="POST" action="{{url_for('main.search')}}">
                  <div class="search-container">
                    {{form.hidden_tag()}}
                    <input type="text" name="searched" class="form-control me-2" placeholder="Class/Professor">
                    <button id="searchButton" type="submit">Search</button>
                  </div>
                </form>
              </li>
      
            </ul>
          </nav>
    </header>
    <main id="content">
        <section class="classSection" id="classReviewSection">
            <h2>Your Reviews</h2>
            </br>
            </br>

            <div class="classReviewsContainer">
                <h3>Your Class Reviews</h3>
                {% for review in class_posts %}
                <section class="classReviews">
                    <h3 class="reviewTitle">Review {{ loop.index }}</h3>
                    <h4 class="reviewRating">{{ review.rating }}/5 Stars</h4>
                    <h4 class="reviewDate">{{ review.date_posted }}</h4>
                    <h4 class="reviewProf">{{ review.professor_name }}</h4>
                    <p class="reviewDesc">{{ review.content }}</p>

                    <!-- Edit and Delete Buttons for the student's reviews -->
                    <div class="edit-delete-buttons">
                        <a href="{{ url_for('main.f_edit_post', id=review.id, post_type='class') }}"
                            class="edit-link">Edit</a>
                        <a href="{{ url_for('main.delete_post', post_id=review.id, post_type='class') }}"
                            class="delete-link">Delete</a>

                    </div>
                </section>
                {% endfor %}
                <h3>Your Professor Reviews</h3>
                {% for review in professor_posts %}
                <section class="classReviews">
                    <h3 class="reviewTitle">Review {{ loop.index }}</h3>
                    <h4 class="reviewRating">{{ review.rating }}/5 Stars</h4>
                    <h4 class="reviewDate">{{ review.date_posted }}</h4>
                    <h4 class="reviewProf">{{ review.professor_name }}</h4>
                    <p class="reviewDesc">{{ review.content }}</p>

                    <!-- Edit and Delete Buttons for the student's reviews -->
                    <div class="edit-delete-buttons">
                        <a href="{{ url_for('main.f_edit_post', id=review.id, post_type='professor') }}"
                            class="edit-link">Edit</a>
                        <a href="{{ url_for('main.delete_post', post_id=review.id, post_type='professor') }}"
                            class="delete-link">Delete</a>

                    </div>
                </section>
                {% endfor %}
            </div>

            <section class="container">
                <button class="revButton" id="prevButton"><span>&#9664;</span> </button>
                <button class="revButton" id="nextButton"><span>&#9654;</span></button>
            </section>
        </section>
    </main>
    <footer id="footer">

        <ul>
            <li><a href="{{ url_for('main.aboutus') }}">About Us</a></li>
            <li><a href="{{ url_for('main.ourMission') }}">Our Mission</a></li>
            <li><a href="{{ url_for('main.contactUs') }}">Contact Us</a></li>
            <li><a href="{{ url_for('main.futurePlans') }}">Future Plans</a></li>



        </ul>
        <p>Site content for Course Reviewer (Group E)</p>
    </footer>
</body>

</html>
{% endblock %}